FROM fedora:latest

RUN dnf install -y autogen libasan libubsan autoconf automake patch texinfo xorg-x11-util-macros systemtap-sdt-devel kernel-tools-libs-devel numactl-devel cmake gdb gcc-c++ git python3-pip make xfsprogs-devel
RUN pip3 install conan
